### ISSUE TITLE
www.openttd.org always shows "Login" instead of "Logout (account name)"

### ISSUE THREAD

**Issue by James103** [OpenTTD/website#96] opened 2019-08-02 16:42 UTC
Whenever I go to any page in www.openttd.org, the footer says "Login" instead of "Logout (account name". This does not happen elsewhere (tested on bananas.openttd.org, servers.openttd.org, account.openttd.org).
When not on www.openttd.org:
![image](https://user-images.githubusercontent.com/37945304/62385559-0db1a080-b51b-11e9-8b45-c4a959ca4751.png)
When on www.openttd.org:
![image](https://user-images.githubusercontent.com/37945304/62385581-199d6280-b51b-11e9-8908-0d47d5eef9c1.png)

**Comment by glx22** [comment] 2019-08-02 17:37
www.openttd.org is fully static and not concerned by login status

**Comment by TrueBrain** [comment] 2019-08-02 20:00
Just because it quacks like a duck ;)

Although our templates look very similar, it doesn't mean they are the same. As @glx mentioned, www.openttd.org is a full static page, where the others are not. Slowly you will see the other pages changing to (semi)static pages too, like servers, etc. Bananas is one of the few that will keep the dynamic behaviour, as, well, it is more appropriate there :D

So this is not a bug. The one thing that does come to mind, that "Login" might be a bit weird as option between there. We could either remove it completely (as only BaNaNaS requires the login these days; and it asks for it when you need to enter it anyway), or change it to something like "Account" or "Manage". If you are up for that, please create a PR to address this (either of the options is fine by me).

Tnx!

**Comment by TrueBrain** [comment] 2019-12-07 09:52
Seems nobody cares enough to fix this :) Closing the issue. Nevertheless, tnx for the report!

**Closed by TrueBrain** 2019-12-07 09:52 UTC
