### ISSUE TITLE
Suggestion: Make author and date added always publicly visible on bananas.openttd.org

### ISSUE THREAD

**Issue by James103** [OpenTTD/website#112] opened 2019-12-05 01:15 UTC
Currently, you can only view the author or date that an item is added to BaNaNaS **only** if it is one of the 10 most recent items added to it. I would like to be able to view the date and/or author for all of the other items that are on BaNaNaS, not just of the 10 most recent items only.

In other words, the author and date for an item in BaNaNaS is publicly visible from the moment it's uploaded and until 10 more items have been uploaded after this item, after which both the author and date are completely hidden.

The main reason to always show date added is so people browsing BaNaNaS on the website can know when an item was added, even if it is several hundred items ago, The main reason to show the author is so people browsing BaNaNaS on the website can know who made the item and added it to BaNaNaS.

Here is an example of the 10 most recent additions:
![image](https://user-images.githubusercontent.com/37945304/70195109-53999380-16ca-11ea-933f-586428dfde10.png)

Here is an example of the rest of BaNaNaS:
![image](https://user-images.githubusercontent.com/37945304/70195137-6b711780-16ca-11ea-8d8a-7b3e5ad6bee5.png)

**Comment by LordAro** [comment] 2019-12-05 07:49
BaNaNaS isn't technically the website, it's a separate system. Unfortunately that system hasn't been migrated to GH (or the new infrastructure) yet, so there's not really anywhere else to put it...

**Comment by TrueBrain** [comment] 2019-12-07 09:50
BaNaNaS is currently not maintained, and these kind of changes are currently not possible. We are still waiting for someone to create BaNaNaSv2.

PS: it was intended back in these days to do this. This was not by accident left out or something. But .. over 12 years ago ;)

Closing ticket for now, as it is not actionable.

**Closed by TrueBrain** 2019-12-07 09:50 UTC
