### ISSUE TITLE
Daily builds are not being updated

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/website#91] opened 2019-07-05 21:49 UTC
The live website is still pointing to a daily build from a month ago.

**Comment by glx22** [comment] 2019-07-05 22:34
But staging works correctly

**Comment by TrueBrain** [comment] 2019-07-06 08:26
The auto-deploy on the kubernetes cluster stopped working for the `production` space; as such, it was told to deploy new versions, but never did.

Initial investigation doesn't show anything; there is no error triggered when this situation happens, so nothing is notified something is in error. Will investigate further, but going to close the issue for now :)

**Closed by TrueBrain** 2019-07-06 08:26 UTC

**Comment by TrueBrain** [comment] 2019-07-06 09:06
Found the root cause:
https://github.com/kubernetes-client/python/issues/819

Now to think about a proper solution ...

**Comment by TrueBrain** [comment] 2019-07-06 09:51
And a fix has landed in the component that was giving the issues:

https://github.com/TrueBrain/OpenTTD-IaC/commit/d261d37ad39cba2394edf3cc3c873956280a741d
